/*
 * This file is generated by jOOQ.
 */
package br.hikarikun92.blogbackendheroku.persistence.jooq.tables


import br.hikarikun92.blogbackendheroku.persistence.jooq.DefaultSchema
import br.hikarikun92.blogbackendheroku.persistence.jooq.tables.records.CommentRecord

import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row6
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Comment(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, CommentRecord>?,
    aliased: Table<CommentRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<CommentRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>comment</code>
         */
        val COMMENT = Comment()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CommentRecord> = CommentRecord::class.java

    /**
     * The column <code>comment.id</code>.
     */
    val ID: TableField<CommentRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>comment.title</code>.
     */
    val TITLE: TableField<CommentRecord, String?> = createField(DSL.name("title"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    /**
     * The column <code>comment.body</code>.
     */
    val BODY: TableField<CommentRecord, String?> = createField(DSL.name("body"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>comment.published_date</code>.
     */
    val PUBLISHED_DATE: TableField<CommentRecord, LocalDateTime?> = createField(DSL.name("published_date"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "")

    /**
     * The column <code>comment.user_id</code>.
     */
    val USER_ID: TableField<CommentRecord, Int?> = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>comment.post_id</code>.
     */
    val POST_ID: TableField<CommentRecord, Int?> = createField(DSL.name("post_id"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<CommentRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<CommentRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>comment</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>comment</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>comment</code> table reference
     */
    constructor(): this(DSL.name("comment"), null)
    override fun getSchema(): Schema = DefaultSchema.DEFAULT_SCHEMA
    override fun getIdentity(): Identity<CommentRecord, Int?> = super.getIdentity() as Identity<CommentRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<CommentRecord> = Internal.createUniqueKey(Comment.COMMENT, DSL.name("KEY_comment_PRIMARY"), arrayOf(Comment.COMMENT.ID), true)
    override fun getKeys(): List<UniqueKey<CommentRecord>> = listOf(
          Internal.createUniqueKey(Comment.COMMENT, DSL.name("KEY_comment_PRIMARY"), arrayOf(Comment.COMMENT.ID), true)
    )
    override fun `as`(alias: String): Comment = Comment(DSL.name(alias), this)
    override fun `as`(alias: Name): Comment = Comment(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Comment = Comment(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Comment = Comment(name, null)

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row6<Int?, String?, String?, LocalDateTime?, Int?, Int?> = super.fieldsRow() as Row6<Int?, String?, String?, LocalDateTime?, Int?, Int?>
}
