/*
 * This file is generated by jOOQ.
 */
package br.hikarikun92.blogbackendheroku.persistence.jooq.tables


import br.hikarikun92.blogbackendheroku.persistence.jooq.DefaultSchema
import br.hikarikun92.blogbackendheroku.persistence.jooq.tables.records.PostRecord

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row4
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Post(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, PostRecord>?,
    aliased: Table<PostRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<PostRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>post</code>
         */
        val POST = Post()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<PostRecord> = PostRecord::class.java

    /**
     * The column <code>post.id</code>.
     */
    val ID: TableField<PostRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>post.title</code>.
     */
    val TITLE: TableField<PostRecord, String?> = createField(DSL.name("title"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    /**
     * The column <code>post.body</code>.
     */
    val BODY: TableField<PostRecord, String?> = createField(DSL.name("body"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>post.user_id</code>.
     */
    val USER_ID: TableField<PostRecord, Int?> = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<PostRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<PostRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>post</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>post</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>post</code> table reference
     */
    constructor(): this(DSL.name("post"), null)
    override fun getSchema(): Schema = DefaultSchema.DEFAULT_SCHEMA
    override fun getIdentity(): Identity<PostRecord, Int?> = super.getIdentity() as Identity<PostRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<PostRecord> = Internal.createUniqueKey(Post.POST, DSL.name("KEY_post_PRIMARY"), arrayOf(Post.POST.ID), true)
    override fun getKeys(): List<UniqueKey<PostRecord>> = listOf(
          Internal.createUniqueKey(Post.POST, DSL.name("KEY_post_PRIMARY"), arrayOf(Post.POST.ID), true)
    )
    override fun `as`(alias: String): Post = Post(DSL.name(alias), this)
    override fun `as`(alias: Name): Post = Post(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Post = Post(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Post = Post(name, null)

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row4<Int?, String?, String?, Int?> = super.fieldsRow() as Row4<Int?, String?, String?, Int?>
}
