/*
 * This file is generated by jOOQ.
 */
package br.hikarikun92.blogbackendheroku.persistence.jooq.tables


import br.hikarikun92.blogbackendheroku.persistence.jooq.DefaultSchema
import br.hikarikun92.blogbackendheroku.persistence.jooq.tables.records.UserCredentialsRecord

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row2
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UserCredentials(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, UserCredentialsRecord>?,
    aliased: Table<UserCredentialsRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<UserCredentialsRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>user_credentials</code>
         */
        val USER_CREDENTIALS = UserCredentials()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<UserCredentialsRecord> = UserCredentialsRecord::class.java

    /**
     * The column <code>user_credentials.user_id</code>.
     */
    val USER_ID: TableField<UserCredentialsRecord, Int?> = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>user_credentials.password</code>.
     */
    val PASSWORD: TableField<UserCredentialsRecord, String?> = createField(DSL.name("password"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<UserCredentialsRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<UserCredentialsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>user_credentials</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>user_credentials</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>user_credentials</code> table reference
     */
    constructor(): this(DSL.name("user_credentials"), null)
    override fun getSchema(): Schema = DefaultSchema.DEFAULT_SCHEMA
    override fun getPrimaryKey(): UniqueKey<UserCredentialsRecord> = Internal.createUniqueKey(UserCredentials.USER_CREDENTIALS, DSL.name("KEY_user_credentials_PRIMARY"), arrayOf(UserCredentials.USER_CREDENTIALS.USER_ID), true)
    override fun getKeys(): List<UniqueKey<UserCredentialsRecord>> = listOf(
          Internal.createUniqueKey(UserCredentials.USER_CREDENTIALS, DSL.name("KEY_user_credentials_PRIMARY"), arrayOf(UserCredentials.USER_CREDENTIALS.USER_ID), true)
    )
    override fun `as`(alias: String): UserCredentials = UserCredentials(DSL.name(alias), this)
    override fun `as`(alias: Name): UserCredentials = UserCredentials(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): UserCredentials = UserCredentials(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): UserCredentials = UserCredentials(name, null)

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row2<Int?, String?> = super.fieldsRow() as Row2<Int?, String?>
}
