/*
 * This file is generated by jOOQ.
 */
package br.hikarikun92.blogbackendheroku.persistence.jooq.tables.records


import br.hikarikun92.blogbackendheroku.persistence.jooq.tables.UserCredentials

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record2
import org.jooq.Row2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UserCredentialsRecord() : UpdatableRecordImpl<UserCredentialsRecord>(UserCredentials.USER_CREDENTIALS), Record2<Int?, String?> {

    var userId: Int?
        set(value) = set(0, value)
        get() = get(0) as Int?

    var password: String?
        set(value) = set(1, value)
        get() = get(1) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row2<Int?, String?> = super.fieldsRow() as Row2<Int?, String?>
    override fun valuesRow(): Row2<Int?, String?> = super.valuesRow() as Row2<Int?, String?>
    override fun field1(): Field<Int?> = UserCredentials.USER_CREDENTIALS.USER_ID
    override fun field2(): Field<String?> = UserCredentials.USER_CREDENTIALS.PASSWORD
    override fun component1(): Int? = userId
    override fun component2(): String? = password
    override fun value1(): Int? = userId
    override fun value2(): String? = password

    override fun value1(value: Int?): UserCredentialsRecord {
        this.userId = value
        return this
    }

    override fun value2(value: String?): UserCredentialsRecord {
        this.password = value
        return this
    }

    override fun values(value1: Int?, value2: String?): UserCredentialsRecord {
        this.value1(value1)
        this.value2(value2)
        return this
    }

    /**
     * Create a detached, initialised UserCredentialsRecord
     */
    constructor(userId: Int? = null, password: String? = null): this() {
        this.userId = userId
        this.password = password
    }
}
